--- #YAML:1.0
name:               Test-Classy
version:            0.04
abstract:           write your unit tests in other modules than *.t
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Data::Inheritable:  0
    Class::Inspector:     0
    Data::Dump:           0
    Module::Find:         0
    Sub::Install:         0
    Test::More:           0.47
    Test::UseAllModules:  0.09
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
